# SELECT * FROM BOOK;

WITH PERIOD_SALES AS (
    SELECT b.BOOK_ID, b.PRICE, s.SALES, b.PRICE * s.SALES TOTAL_SALES
    FROM BOOK b
    JOIN (
        SELECT BOOK_ID, SUM(SALES) SALES
        FROM BOOK_SALES
        WHERE SALES_DATE LIKE '2022-01%'
        GROUP BY BOOK_ID
    ) s
    ON b.BOOK_ID = s.BOOK_ID
)

SELECT b.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, SUM(s.TOTAL_SALES) TOTAL_SALES
FROM BOOK b
JOIN PERIOD_SALES s
ON b.BOOK_ID = s.BOOK_ID
JOIN AUTHOR a
ON b.AUTHOR_ID = a.AUTHOR_ID
GROUP BY b.AUTHOR_ID, b.CATEGORY
ORDER BY b.AUTHOR_ID ASC, b.CATEGORY DESC;