SELECT SUBSTR(o.SALES_DATE, 1, 4) AS "YEAR", 
    SUBSTR(o.SALES_DATE, 6, 2) AS "MONTH",
    u.GENDER,
    COUNT(DISTINCT o.USER_ID) AS "USERS"
FROM ONLINE_SALE AS o, USER_INFO AS u
WHERE o.USER_ID = u.USER_ID AND GENDER IS NOT NULL
GROUP BY 1, 2, 3
ORDER BY 1, 2, 3