SELECT YEAR, MONTH, GENDER, COUNT(DISTINCT USER_ID) AS "USERS"
FROM (SELECT SUBSTR(o.SALES_DATE, 1, 4) AS "YEAR", 
        SUBSTR(o.SALES_DATE, 6, 2) AS "MONTH", 
        SUBSTR(o.SALES_DATE, 1, 7) AS "TMP",
        u.GENDER,
        o.USER_ID
    FROM ONLINE_SALE AS o, USER_INFO AS u
    WHERE o.USER_ID = u.USER_ID AND GENDER IS NOT NULL) AS tbl1
GROUP BY TMP, GENDER
ORDER BY YEAR, MONTH, GENDER
    


