WITH RECURSIVE ECOLI_GEN_DATA AS (
    SELECT ID, PARENT_ID, 1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT e.ID, e.PARENT_ID, GEN + 1 AS GEN
    FROM ECOLI_DATA e
    JOIN ECOLI_GEN_DATA g
    ON e.PARENT_ID = g.ID
)

SELECT ID 
FROM ECOLI_GEN_DATA
WHERE GEN = 3
ORDER BY ID;