WITH DISCOUNT_POLICY AS (
    SELECT CAR_TYPE, SUBSTRING_INDEX(DURATION_TYPE, '일', 1) AS DURATION, 100 - DISCOUNT_RATE AS DISCOUNT
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE IN ('세단', 'SUV')
), IMPOSSIBLE AS (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE (START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01') 
)

SELECT CAR_ID, CAR_TYPE, 
    ROUND(CASE 
        WHEN CAR_TYPE = '세단' 
        THEN DAILY_FEE * 30 * (SELECT DISCOUNT FROM DISCOUNT_POLICY WHERE CAR_TYPE = '세단' AND DURATION = 30) / 100
        ELSE DAILY_FEE * 30 * (SELECT DISCOUNT FROM DISCOUNT_POLICY WHERE CAR_TYPE = 'SUV' AND DURATION = 30) / 100
    END) AS FEE
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_TYPE IN ('세단', 'SUV')
AND CAR_ID NOT IN (SELECT CAR_ID FROM IMPOSSIBLE)
HAVING FEE >= 500000 AND FEE <= 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC