SELECT u.USER_ID, u.NICKNAME, 
    CONCAT_WS(" ", u.CITY, u.STREET_ADDRESS1, u.STREET_ADDRESS2) AS "전체주소",
    CONCAT_WS("-", LEFT(u.TLNO, 3), MID(u.TLNO, 4, 4), RIGHT(u.TLNO, 4)) AS "전화번호"
FROM USED_GOODS_USER AS u
JOIN (SELECT WRITER_ID, COUNT(*) AS "count" FROM USED_GOODS_BOARD GROUP BY WRITER_ID) b
ON u.USER_ID = b.WRITER_ID
WHERE b.count >= 3
ORDER BY u.USER_ID DESC