SELECT tbl1.CATEGORY, tbl1.PRICE AS "MAX_PRICE", tbl1.PRODUCT_NAME
FROM FOOD_PRODUCT AS tbl1
JOIN (SELECT CATEGORY, MAX(PRICE) AS "MAX_PRICE" FROM FOOD_PRODUCT GROUP BY CATEGORY) AS tbl2
ON tbl1.CATEGORY = tbl2.CATEGORY AND tbl1.PRICE = tbl2.MAX_PRICE
WHERE tbl1.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY MAX_PRICE DESC