WITH ON_RENTAL AS (
    SELECT DISTINCT CAR_ID, "대여중" AVAILABILITY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16'
)

SELECT a.CAR_ID, IFNULL(b.AVAILABILITY, '대여 가능') AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY a
LEFT JOIN ON_RENTAL b
ON a.CAR_ID = b.CAR_ID
GROUP BY a.CAR_ID
ORDER BY a.CAR_ID DESC