WITH ECOLI_QUARTER AS (
    SELECT ID, 
        (CASE 
            WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 1 AND 3 THEN '1Q'
            WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 4 AND 6 THEN '2Q'
            WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 7 AND 9 THEN '3Q'
            ELSE '4Q'
        END) AS QUARTER
    FROM ECOLI_DATA
)

SELECT QUARTER, COUNT(ID) AS ECOLI_COUNT 
FROM ECOLI_QUARTER
GROUP BY 1
ORDER BY 1