SELECT CATEGORY, SUM(SALES) AS 'TOTAL_SALES'
FROM (SELECT b.BOOK_ID, b.CATEGORY, s.SALES 
      FROM BOOK AS b JOIN BOOK_SALES s 
      ON b.BOOK_ID = s.BOOK_ID 
      WHERE s.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31') AS tb
GROUP BY CATEGORY
ORDER BY CATEGORY