SELECT p.PRODUCT_CODE, p.PRICE * o.AMOUNT AS "SALES"
FROM PRODUCT AS p
JOIN (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS "AMOUNT" FROM OFFLINE_SALE GROUP BY PRODUCT_ID) AS o
ON p.PRODUCT_ID = o.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE
