WITH C AS (
    SELECT 
        RANK() OVER (ORDER BY CAST(SUBSTRING_INDEX(DURATION_TYPE, '일', 1) AS UNSIGNED) ASC) AS PLAN_ID, 
        (100 - DISCOUNT_RATE) DISCOUNT_RATE
     FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭'
)

SELECT A.HISTORY_ID,
    ROUND(CASE 
        WHEN A.DURATION >= 90 THEN A.DAILY_FEE * A.DURATION * (SELECT C.DISCOUNT_RATE FROM C WHERE C.PLAN_ID = 3) / 100
        WHEN A.DURATION >= 30 THEN A.DAILY_FEE * A.DURATION * (SELECT C.DISCOUNT_RATE FROM C WHERE C.PLAN_ID = 2) / 100
        WHEN A.DURATION >= 7 THEN A.DAILY_FEE * A.DURATION * (SELECT C.DISCOUNT_RATE FROM C WHERE C.PLAN_ID = 1) / 100
        ELSE A.DAILY_FEE * A.DURATION
    END) AS FEE
FROM (SELECT H.HISTORY_ID, DATEDIFF(H.END_DATE, START_DATE) + 1 AS DURATION, DAILY_FEE 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN CAR_RENTAL_COMPANY_CAR B
    ON H.CAR_ID = B.CAR_ID AND B.CAR_TYPE = '트럭') A
ORDER BY FEE DESC, HISTORY_ID DESC