WITH GRADE AS (
    SELECT EMP_NO, AVG(SCORE) AS SCORE 
    FROM HR_GRADE 
    GROUP BY EMP_NO
)

SELECT e.EMP_NO, e.EMP_NAME, 
    CASE 
        WHEN g.SCORE >= 96 THEN 'S'
        WHEN g.SCORE >= 90 THEN 'A'
        WHEN g.SCORE >= 80 THEN 'B'
        ELSE 'C'
    END GRADE,
    CASE 
        WHEN g.SCORE >= 96 THEN e.SAL * 0.2
        WHEN g.SCORE >= 90 THEN e.SAL * 0.15
        WHEN g.SCORE >= 80 THEN e.SAL * 0.1
        ELSE 0
    END BONUS
FROM HR_EMPLOYEES e
JOIN GRADE g ON e.EMP_NO = g.EMP_NO
ORDER BY e.EMP_NO ASC