WITH BEST AS (
    SELECT COUNT(REVIEW_ID) NUM FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY 1 DESC
    LIMIT 1
)

SELECT 
p.MEMBER_NAME, r.REVIEW_TEXT, DATE_FORMAT(r.REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM REST_REVIEW r
JOIN MEMBER_PROFILE p
ON r.MEMBER_ID = p.MEMBER_ID
WHERE r.MEMBER_ID IN (
    SELECT MEMBER_ID FROM (
        SELECT MEMBER_ID, COUNT(REVIEW_ID) NUM 
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
    ) a
    JOIN BEST B
    ON a.NUM = b.NUM
)
ORDER BY r.REVIEW_DATE ASC, r.REVIEW_TEXT ASC


