WITH RARE_ITEM AS (
    SELECT ITEM_ID 
    FROM ITEM_INFO 
    WHERE RARITY = 'RARE'
)

SELECT T.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_TREE T
JOIN ITEM_INFO I
ON T.ITEM_ID = I.ITEM_ID
WHERE PARENT_ITEM_ID IN (SELECT ITEM_ID FROM RARE_ITEM)
ORDER BY 1 DESC