WITH HIS AS (
    SELECT CAR_ID, COUNT(*)
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)

# SELECT MONTH(START_DATE) MONTH, CAR_ID, COUNT(*) RECORDS 
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE MONTH(START_DATE) BETWEEN 8 AND 10
# AND CAR_ID IN (SELECT CAR_ID FROM MORE_FIVE)
# GROUP BY MONTH(START_DATE), CAR_ID
# ORDER BY MONTH ASC, CAR_ID DESC;


# WITH HIS AS (
#     SELECT CAR_ID, COUNT(CAR_ID) AS CNT, START_DATE, END_DATE
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#     WHERE DATE_FORMAT(START_DATE, '%Y-%m') >'2022-07' AND DATE_FORMAT(START_DATE, '%Y-%m') < '2022-11'
#     GROUP BY CAR_ID
#     HAVING COUNT(*) > 4
# )
SELECT MONTH(C.START_DATE) AS MONTH, C.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C JOIN HIS H ON C.CAR_ID=H.CAR_ID and month(c.start_date) between 8 and 10
GROUP BY MONTH, CAR_ID
ORDER BY MONTH ASC, CAR_ID DESC;