WITH HR_SCORE AS (
    SELECT EMP_NO, YEAR, SUM(SCORE) SCORE FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
)

SELECT S.SCORE, S.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_SCORE S
JOIN HR_EMPLOYEES E
ON S.EMP_NO = E.EMP_NO
WHERE S.SCORE = (SELECT MAX(SCORE) FROM HR_SCORE)