WITH UNDER_TEN AS (
    SELECT ID, FISH_TYPE, IFNULL(LENGTH, 10) LENGTH, TIME
    FROM FISH_INFO
)

SELECT COUNT(ID) FISH_COUNT, MAX(LENGTH) MAX_LENGTH, FISH_TYPE
FROM UNDER_TEN
GROUP BY FISH_TYPE
HAVING AVG(LENGTH) >= 33
ORDER BY FISH_TYPE ASC