SELECT i.REST_ID, i.REST_NAME, i.FOOD_TYPE, i.FAVORITES, i.ADDRESS, r.SCORE
FROM REST_INFO AS i
JOIN (SELECT REST_ID, ROUND(SUM(REVIEW_SCORE) / COUNT(*), 2) AS "SCORE" 
      FROM REST_REVIEW 
      GROUP BY REST_ID) AS r
ON i.REST_ID = r.REST_ID
WHERE ADDRESS REGEXP '^서울'
ORDER BY SCORE DESC, FAVORITES DESC